### ISSUE TITLE
Word2vec cause Error at VEGA

### ISSUE THREAD

**Issue by ghost** [fixstars/clpy#12]
# Word2vec cause Error at AMD VEGA
## Environment
* OS: Ubuntu 16.04.4 LTS
* CPU: Core i7-4790
* MEM: 8GB
* GPU: AMD Radeon Vega Frontier Edition (Air Cooled)
* SDK: AMD APP SDK 3.0
* python: 3.6.4
* clpy: b59da4c3
```
chainer==3.3.0
clpy==2.1.0a0
Cython==0.28.3
fastrlock==0.3
filelock==3.0.4
numpy==1.14.3
protobuf==3.5.2.post1
six==1.11.0
```

## result
```
$ python train_word2vec.py -g 0
/home/kitawaki/.pyenv/versions/clpy/lib/python3.6/site-packages/chainer-3.3.0-py3.6.egg/chainer/backends/cuda.py:85: UserWarning: cuDNN is not enabled.
Please reinstall CuPy after you install cudnn
(see https://docs-cupy.chainer.org/en/stable/install.html#install-cupy-with-cudnn-and-nccl).
  'cuDNN is not enabled.\n'
GPU: 0
# unit: 100
Window: 5
Minibatch-size: 1000
# epoch: 20
Training model: skipgram
Output type: hsm

n_vocab: 10000
data length: 929589
Memory access fault by GPU node-1 on address 0x19903c0a000. Reason: Page not present or supervisor privilege.
中止 (コアダンプ)

```

**Comment by ghost** [comment]
See #13.

**Comment by ghost** [comment]
I updated the training time in the [wiki page](https://github.com/fixstars/clpy/wiki/chainer_example_performance_report#chainers-example-execution-timesec) with the version where this issue has been fixed.
